---
- name: Converge
  hosts: all
  tasks:
    - name: "Include caddy_server"
      include_role:
        name: "caddy_server"
      vars:
        caddy_config_mode: Caddyfile
        caddy_caddyfile: |
          localhost:80

          respond "Hello World!"
