---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get running services
      service_facts:

    - name: Verify that caddy service is running and enabled
      assert:
        that:
          - ansible_facts.services["caddy.service"].state == "running"
          - ansible_facts.services["caddy.service"].status == "enabled"

    - name: Load site
      uri:
        url: "http://localhost:80"
        return_content: yes
      register: caddy_site

    - name: Verify that site got served
      assert:
        that: '"Hello World!" in caddy_site.content'
