authors:
- Max Hösel <ansible@maxhoesel.de>
build_ignore:
- .circleci
- .github
- .vscode
- dist
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- .yamllint
- '*.tar.gz'
- .venv
- .tox
- .pytest_cache
- scripts
- .pre-commit-config.yaml
- .readthedocs.yaml
- pyproject.toml
- requirements.txt
- '**/requirements.txt'
dependencies:
  community.general: '>=2.0.0'
description: A collection to manage a caddy installation
issues: https://github.com/maxhoesel-ansible/ansible-collection-caddy/issues
license_file: LICENSE
name: caddy
namespace: maxhoesel
readme: README.md
repository: https://github.com/maxhoesel-ansible/ansible-collection-caddy
tags:
- caddy
- webserver
- linux
- application
version: 3.0.0
