authors:
- Max Hösel <ansible@maxhoesel.de>
build_ignore:
- .circleci
- .github
- tests
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- pyproject.toml
- tox.ini
- .yamllint
- .ansible-lint
- .pre-commit-config.yaml
- '*.tar.gz'
- .venv
- .tox
- .pytest_cache
- scripts
- requirements.txt
- requirements-molecule.txt
- '**/requirements-molecule.txt'
- '**/requirements.txt'
dependencies:
  community.general: '>=2.0.0'
description: A collection to manage a caddy installation
issues: https://github.com/maxhoesel-ansible/ansible-collection-caddy/issues
license_file: LICENSE
name: caddy
namespace: maxhoesel
readme: README.md
repository: https://github.com/maxhoesel-ansible/ansible-collection-caddy
tags:
- caddy
- webserver
version: 1.0.1
