- hosts: "ubuntu:debian"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

- hosts: archlinux
  tasks:
    - name: Initialize keyring # noqa no-changed-when
      shell: pacman-key --init && pacman -Sy archlinux-keyring --noconfirm
    - name: Upgrade system
      community.general.pacman:
        update_cache: yes
        upgrade: yes
