---
- name: Reload Caddy
  ansible.builtin.systemd:
    name: caddy.service
    state: reloaded
    daemon_reload: true
  when: caddy_config_mode == "Caddyfile"

- name: Restart Caddy
  ansible.builtin.systemd:
    name: "{{ caddy_server_service[caddy_config_mode] }}"
    state: restarted
    daemon_reload: true
