---
- name: Reload Caddy
  service:
    name: "caddy"
    state: reloaded
  when: (caddy_config_mode == 'Caddyfile')

- name: Reload Systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
