---
- name: caddy service is stopped and disabled
  ansible.builtin.systemd:
    name: "caddy"
    state: stopped
    enabled: false

- name: caddy-api service is started and enabled
  ansible.builtin.systemd:
    name: "caddy-api"
    state: started
    enabled: true

- name: JSON configuration is applied
  maxhoesel.caddy.caddy_load:
    config: "{{ caddy_json_config }}"
