---
- name: Systemd unit override directory is present
  ansible.builtin.file:
    path: "/etc/systemd/system/caddy.service.d"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Systemd unit override config is present
  ansible.builtin.template:
    src: "caddy.service.j2"
    dest: "/etc/systemd/system/caddy.service.d/override.conf"
    owner: root
    group: root
    mode: "0644"
  notify:
    - "Reload Systemd"
    - "Reload Caddy"
