---
- name: Requirements are installed
  package:
    name:
      - "{{ 'python3-requests' if ansible_python_version is version('3', '>=') else 'python-requests' }}"
      - dnf-command(copr)

- name: Caddy repository is enabled
  community.general.copr:
    name: "@caddy/caddy"
    chroot: "epel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}"

- name: Caddy is installed
  package:
    name: caddy
