---
- name: Update script is present
  ansible.builtin.template:
    src: "caddy-custom-updater.sh.j2"
    dest: "/usr/local/bin/caddy-custom-updater"
    owner: root
    group: root
    mode: "0755"

- name: Update timer is present
  ansible.builtin.template:
    src: "caddy-custom-updater.timer.j2"
    dest: "/etc/systemd/system/caddy-custom-updater.timer"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload Systemd
- name: Custom update service is present
  ansible.builtin.template:
    src: "caddy-custom-updater.service.j2"
    dest: "/etc/systemd/system/caddy-custom-updater.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload Systemd

- name: Custom update timer is present
  ansible.builtin.systemd_service:
    name: "caddy-custom-updater.timer"
    state: "{{ caddy_custom_update_timer_enabled | ternary('started', 'stopped') }}"
    enabled: "{{ caddy_custom_update_timer_enabled }}"
