name: Auto-Merge Dependabot PRs

on:
  pull_request:
    branches:
      # the dependabot-auto-merge action actually checks the PR author - this is just an early exit
      # for PRs that are obviously not dependabot-related
      - 'dependabot/*'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          command: squash and merge
          approve: true
          github-token: ${{ secrets.DEPENDABOT_AUTOMERGE_PAT }}
